import Footer from '@/components/Footer'
import Header from '@/components/Header'
import Head from 'next/head'

export default function About() {
  return (
    <>
      <Head>
        <title>Imagineshop - About</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.ico" />
      </Head>
      <h1>About works</h1>
    </>
  )
}