import { useContext, useEffect, useState } from 'react'
import Head from 'next/head'
import Image from 'next/image';
import { faX } from '@fortawesome/free-solid-svg-icons'
import { ShoppingCartContext } from '@/contexts/ShoppingCartContext'
import { IProduct } from '@/types'

import {
  Main,
  Title,
  SubTitle,
  ShoppingCartContainer,
  Separator,
  ButtonContainer,
  DeleteIcon,
  Product,
  ProductName,
  ProductPrice,
  ShoppingCartPayment,
  PaymentTitle,
  PaymentValue,
  PaymentShipping,
  PaymentTotal,
  LoginTitle,
  InputGroup,
  Button
} from './styles'

export default function ShoppingCart() {
  const { 
    getProducts,
    deleteProduct,
    getTotalValue,
    getTotalProducts,
    getShippingValue
  } = useContext(ShoppingCartContext)

  const [products, setProducts] = useState<IProduct[]>([])
  const [refresh, setRefresh] = useState<number>(0);

  useEffect(() => {
    const values = getProducts();
    setProducts(values);
  }, [getProducts, refresh])

  const handleDeleteProduct = (id: string) => {
    deleteProduct(id);
    setRefresh(oldValue => oldValue + 1);
  }

  return (
    <>
      <Head>
        <title>ImagineShop - Cart</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.ico" />
      </Head>
      <Main>
        <Title>Meu Carrinho</Title>
        <SubTitle>Produtos</SubTitle>
        <ShoppingCartContainer>
          <section>
            <Separator />
            {
              products && products.map(product => (
                <div key={product._id}>
                  <ButtonContainer>
                  <button onClick={() => handleDeleteProduct(product._id)}>
                      <DeleteIcon icon={faX}></DeleteIcon>
                    </button>
                  </ButtonContainer>
                  <Product>
                    <div>
                      <Image src={product.image} width={180} height={180} alt={product.name} />
                    </div>
                    <ProductName>{product.name}</ProductName>
                    <ProductPrice>{product.formattedPrice}</ProductPrice>
                  </Product>
                  <Separator />
                </div>
              ))
            }
          </section>
          <section>
            <ShoppingCartPayment>
              <PaymentTitle>1. Resumo do pedido</PaymentTitle>
              <PaymentValue><span>{products.length} Produtos</span> <span>{getTotalProducts()}</span></PaymentValue>
              <PaymentShipping><span>Frete</span> <span>{getShippingValue()}</span></PaymentShipping>
              <PaymentTotal><span>Total</span> <span>{getTotalValue()}</span></PaymentTotal>
              <Separator />
              <LoginTitle>2. Login</LoginTitle>
              <InputGroup>
                <span>E-MAIL:</span>
                <input type="text" />
              </InputGroup>
              <InputGroup>
                <span>SENHA:</span>
                <input type="password" />
              </InputGroup>
              <Button>
                Continuar
              </Button>
            </ShoppingCartPayment>
          </section>
        </ShoppingCartContainer>
      </Main>
    </>
  )
}
