import Banner from '@/components/Banner'
import Products from '@/components/Products'
import { GetServerSideProps } from 'next'
import Head from 'next/head'

import BannerImage from '../../../public/images/banner.png'
/* import Celular1 from '../../../public/images/celular1.png'
import Celular2 from '../../../public/images/celular2.png'
import Celular3 from '../../../public/images/celular3.jpg' */
import { Main } from './styles'

/* const productsAPI = [
  {
    _id: "1",
    name: "Celular1",
    image: Celular1,
    price: 10,
    formattedPrice: "R$ 10.00",
    splitPrice: "R$ 10.00"
  },
  {
    _id: "2",
    name: "Celular2",
    image: Celular2,
    price: 15,
    formattedPrice: "R$ 15.00",
    splitPrice: "R$ 15.00"
  },
  {
    _id: "3",
    name: "Celular3",
    image: Celular3,
    price: 20,
    formattedPrice: "R$ 20.00",
    splitPrice: "R$ 20.00"
  },
  {
    _id: "4",
    name: "Celular1",
    image: Celular1,
    price: 10,
    formattedPrice: "R$ 10.00",
    splitPrice: "R$ 10.00"
  },
  {
    _id: "5",
    name: "Celular2",
    image: Celular2,
    price: 15,
    formattedPrice: "R$ 15.00",
    splitPrice: "R$ 15.00"
  },
  {
    _id: "6",
    name: "Celular3",
    image: Celular3,
    price: 20,
    formattedPrice: "R$ 20.00",
    splitPrice: "R$ 20.00"
  }
] */

export const getServerSideProps: GetServerSideProps = async () => {
  const api = 'https://imagineshop.fly.dev';
  const result = await fetch(`${api}/products`);
  const data = await result.json();
  data.forEach((product: any) => {
    product.image = `${api}/uploads/${product.fileName}`;
    product.formattedPrice = (new Intl.NumberFormat('pt-BR', { style:'currency', currency: 'BRL'})).format(product.price);
    product.splitPrice = (new Intl.NumberFormat('pt-BR', { style:'currency', currency: 'BRL'})).format(product.price/10);
  });
  return {
    props: {
      productsApi: data
    }
  }
}

export default function Home({ productsApi }: any) {
  return (
    <>
      <Head>
        <title>Imagineshop - Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.ico" />
      </Head>
      <Main>
        <>
        <Banner image={BannerImage} width={1140} height={325} />
        <Products products={productsApi} />
        </>
      </Main>
    </>
  )
}
