import Banner from '@/components/Banner'
import Head from 'next/head'

import BannerImage from '../../public/images/banner.png'

export default function Home() {
  return (
    <>
      <Head>
        <title>Imagineshop - Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.ico" />
      </Head>

      <>
        <Banner image={BannerImage} width={1140} height={325} />
      </>
    </>
  )
}
